import { HeritageItem } from '../types';


export const UI_TEXT = {
  zh: {
    title: '为什么湘江北去？',
    subtitle: '因为世界上所有的水都是湘江之水，包括泪水',
    back: '返回',
    history: '历史',
    related: '相关遗址',
    reimagine: '重想象此地',
    prompt: '用文字描述你想看到的样子...',
    generate: '生成',
    generating: '生成中...',
    download: '下载'
  },
  en: {
    title: 'Why Does the Xiang River Flow North?',
    subtitle: 'Because all water in the world is Xiang River water — including tears',
    back: 'Back',
    history: 'History',
    related: 'Related Sites',
    reimagine: 'Reimagine This Place',
    prompt: 'Describe what you want to see...',
    generate: 'Generate',
    generating: 'Generating...',
    download: 'Download'
  }
} as const;

export const FEATURED_HERITAGE_ITEMS: HeritageItem[] = [
  {
    id: 'cn-1',
    nameZh: '万里长城',
    nameEn: 'The Great Wall',
    location: 'Beijing / Northern China',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 40.4319, lng: 116.5704 },
    category: 'Tangible',
    descriptionZh: '横跨中国北部的古代军事防御工程，人类历史上最宏大的建筑奇迹之一。宛如巨龙蜿蜒于崇山峻岭之间，守护着古老文明的疆土。',
    descriptionEn: 'A series of fortifications made of stone, brick, tampered earth, wood, and other materials, generally built along an east-to-west line across the historical northern borders of China.',
    imageUrl: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?q=80&w=2070&auto=format&fit=crop',
    era: '7th Century BC - 1644 AD'
  },
  {
    id: 'cn-2',
    nameZh: '北京故宫',
    nameEn: 'The Palace Museum (Forbidden City)',
    location: 'Beijing',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 39.9163, lng: 116.3972 },
    category: 'Tangible',
    descriptionZh: '明清两代皇宫，世界现存规模最大、保存最完整的木结构古建筑群。',
    descriptionEn: 'The largest and most complete complex of ancient wooden structures in the world.',
    imageUrl: 'https://images.unsplash.com/photo-1517332712256-6fb136b2d6a3?w=2000',
    era: '1406–1912 AD'
  },
  {
    id: 'cn-3',
    nameZh: '秦始皇陵及兵马俑',
    nameEn: 'Mausoleum of the First Qin Emperor & Terracotta Army',
    location: 'Xi\'an, Shaanxi',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 34.3841, lng: 109.2784 },
    category: 'Tangible',
    descriptionZh: '8000余尊陶俑组成的地下军队，规模宏大的帝王陵寝。',
    descriptionEn: 'An army of over 8,000 life-sized terracotta warriors guarding the First Emperor.',
    imageUrl: 'https://images.unsplash.com/photo-1538333702850-03aa4a7b9b6b?w=2000',
    era: '221–210 BC'
  },
  {
    id: 'cn-4',
    nameZh: '敦煌莫高窟',
    nameEn: 'Mogao Caves',
    location: 'Dunhuang, Gansu',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 40.0374, lng: 94.8042 },
    category: 'Tangible',
    descriptionZh: '丝绸之路上的佛教艺术宝库，492个石窟，45000平米壁画。',
    descriptionEn: 'The greatest repository of Buddhist art on the Silk Road.',
    imageUrl: 'https://images.unsplash.com/photo-1627894486535-251d9a04a2f4?w=2000',
    era: '366–1368 AD'
  },
  {
    id: 'cn-5',
    nameZh: '布达拉宫',
    nameEn: 'Potala Palace',
    location: 'Lhasa, Tibet',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 29.6573, lng: 91.1172 },
    category: 'Tangible',
    descriptionZh: '世界海拔最高的宫殿建筑群，藏式建筑巅峰之作。',
    descriptionEn: 'The highest palace in the world, winter palace of the Dalai Lamas.',
    imageUrl: 'https://images.unsplash.com/photo-1553272725-086100aecf5e?w=2000',
    era: '7th Century – 1645 AD'
  },
  {
    id: 'cn-6',
    nameZh: '丽江古城',
    nameEn: 'Old Town of Lijiang',
    location: 'Lijiang, Yunnan',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 26.8720, lng: 100.2337 },
    category: 'Tangible',
    descriptionZh: '纳西族古城，无城墙的东方威尼斯，水系与古巷交织。',
    descriptionEn: 'Ancient town of the Naxi people, known as the "Venice of the East".',
    imageUrl: 'https://images.unsplash.com/photo-1558499933-9a08e3d1d7c8?w=2000',
    era: 'Song Dynasty – Present'
  },
  {
    id: 'cn-7',
    nameZh: '苏州古典园林',
    nameEn: 'Classical Gardens of Suzhou',
    location: 'Suzhou, Jiangsu',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 31.3160, lng: 120.6180 },
    category: 'Tangible',
    descriptionZh: '中国私家园林的巅峰代表，拙政园、留园等9座园林。',
    descriptionEn: 'The pinnacle of Chinese classical garden design.',
    imageUrl: 'https://images.unsplash.com/photo-1593697821252-0c3f8d3b2394?w=2000',
    era: '11th–19th Century'
  },
  {
    id: 'cn-8',
    nameZh: '颐和园',
    nameEn: 'Summer Palace',
    location: 'Beijing',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 39.9990, lng: 116.2700 },
    category: 'Tangible',
    descriptionZh: '清代皇家园林，集中国古典园林之大成，长廊万寿山昆明湖。',
    descriptionEn: 'Imperial garden of the Qing Dynasty, masterpiece of Chinese landscape.',
    imageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=2000',
    era: '1750–1888 AD'
  },
  {
    id: 'cn-9',
    nameZh: '承德避暑山庄',
    nameEn: 'Mountain Resort, Chengde',
    location: 'Chengde, Hebei',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 40.9900, lng: 117.9400 },
    category: 'Tangible',
    descriptionZh: '清代最大的皇家园林，康熙乾隆行宫，融合汉满蒙藏建筑风格。',
    descriptionEn: 'Largest existing imperial garden in China, built by Emperors Kangxi and Qianlong.',
    imageUrl: 'https://images.unsplash.com/photo-1588421277-5e8e7e5d9e7e?w=2000',
    era: '1703–1792 AD'
  },
  {
    id: 'cn-10',
    nameZh: '龙门石窟',
    nameEn: 'Longmen Grottoes',
    location: 'Luoyang, Henan',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 34.5552, lng: 112.4700 },
    category: 'Tangible',
    descriptionZh: '北魏至唐代开凿的佛教石窟，卢舍那大佛高17.14米。',
    descriptionEn: 'Buddhist grottoes with the 17.14m-tall Lushena Buddha.',
    imageUrl: 'https://images.unsplash.com/photo-1593693411134-8e6d1d64e1e9?w=2000',
    era: '493–1127 AD'
  },
  {
    id: 'cn-11',
    nameZh: '中医针灸',
    nameEn: 'Traditional Chinese Medicine Acupuncture',
    location: 'Nationwide',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 35.0000, lng: 105.0000 },
    category: 'Intangible',
    descriptionZh: '中国传统医学核心技艺，2010年列入人类非物质文化遗产代表作名录。',
    descriptionEn: 'Core technique of Traditional Chinese Medicine, UNESCO Intangible Heritage.',
    imageUrl: 'https://images.unsplash.com/photo-1603393938459-0b3b1d2d8c3e?w=2000',
    era: 'Ancient – Present'
  },
  {
    id: 'cn-12',
    nameZh: '京剧',
    nameEn: 'Peking Opera',
    location: 'Beijing & Nationwide',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 39.9042, lng: 116.4074 },
    category: 'Intangible',
    descriptionZh: '中国国粹，唱念做打，脸谱与身段的艺术。',
    descriptionEn: 'The quintessence of Chinese culture, combining music, vocal performance, mime, dance and acrobatics.',
    imageUrl: 'https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=2000',
    era: '1790 – Present'
  },
  {
    id: 'it-1',
    nameZh: '罗马斗兽场',
    nameEn: 'Colosseum',
    location: 'Rome, Lazio',
    country: 'Italy',
    continent: 'Europe',
    coordinates: { lat: 41.8902, lng: 12.4922 },
    category: 'Tangible',
    descriptionZh: '古罗马最大的圆形剧场，可容纳8万观众，见证了角斗士的生死搏杀与帝国的辉煌。',
    descriptionEn: 'The largest ancient amphitheatre ever built, symbol of Imperial Rome\'s power and entertainment.',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=2000',
    era: '70–80 AD'
  },
  {
    id: 'it-2',
    nameZh: '威尼斯及其潟湖',
    nameEn: 'Venice and its Lagoon',
    location: 'Venice',
    country: 'Italy',
    continent: 'Europe',
    coordinates: { lat: 45.4408, lng: 12.3155 },
    category: 'Tangible',
    descriptionZh: '水上之城，118个岛屿由400余座桥梁连接，圣马可广场与叹息桥举世闻名。',
    descriptionEn: 'A city built on 118 islands with canals instead of streets, a masterpiece of human ingenuity.',
    imageUrl: 'https://images.unsplash.com/photo-1514890547357-a94ee2e1a69c?w=2000',
    era: '5th Century – Present'
  },
  {
    id: 'it-3',
    nameZh: '庞贝古城',
    nameEn: 'Pompeii',
    location: 'Campania',
    country: 'Italy',
    continent: 'Europe',
    coordinates: { lat: 40.7462, lng: 14.4989 },
    category: 'Tangible',
    descriptionZh: '被维苏威火山灰埋没的古罗马城市，时间定格在公元79年，完整保留了当时生活。',
    descriptionEn: 'Roman city frozen in time by the eruption of Mount Vesuvius in 79 AD.',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=2000',
    era: '6th Century BC – 79 AD'
  },
  {
    id: 'fr-1',
    nameZh: '凡尔赛宫',
    nameEn: 'Palace of Versailles',
    location: 'Versailles',
    country: 'France',
    continent: 'Europe',
    coordinates: { lat: 48.8049, lng: 2.1204 },
    category: 'Tangible',
    descriptionZh: '太阳王路易十四的奢华宫殿，镜厅与皇家花园象征绝对君权巅峰。',
    descriptionEn: 'Symbol of absolute monarchy, famous for the Hall of Mirrors and gardens.',
    imageUrl: 'https://images.unsplash.com/photo-1565060169113-585a0657c79e?w=2000',
    era: '1661–1715 AD'
  },
  {
    id: 'fr-2',
    nameZh: '巴黎塞纳河畔',
    nameEn: 'Paris, Banks of the Seine',
    location: 'Paris',
    country: 'France',
    continent: 'Europe',
    coordinates: { lat: 48.8566, lng: 2.3522 },
    category: 'Tangible',
    descriptionZh: '从埃菲尔铁塔到巴黎圣母院，塞纳河串联起巴黎最伟大的建筑群。',
    descriptionEn: 'From the Eiffel Tower to Notre-Dame, the Seine links Paris\'s greatest monuments.',
    imageUrl: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=2000',
    era: 'Middle Ages – Present'
  },
  {
    id: 'fr-3',
    nameZh: '蒙圣米歇尔',
    nameEn: 'Mont-Saint-Michel',
    location: 'Normandy',
    country: 'France',
    continent: 'Europe',
    coordinates: { lat: 48.6361, lng: -1.5115 },
    category: 'Tangible',
    descriptionZh: '潮汐岛上的中世纪修道院，被称为“西方奇迹”。',
    descriptionEn: 'Medieval abbey on a tidal island, known as the "Wonder of the West".',
    imageUrl: 'https://images.unsplash.com/photo-1579618686842-7e1733a4c1ff?w=2000',
    era: '8th Century – Present'
  },
  {
    id: 'gr-1',
    nameZh: '雅典卫城',
    nameEn: 'Acropolis of Athens',
    location: 'Athens',
    country: 'Greece',
    continent: 'Europe',
    coordinates: { lat: 37.9715, lng: 23.7257 },
    category: 'Tangible',
    descriptionZh: '西方文明的摇篮，帕特农神庙屹立于圣岩之上。',
    descriptionEn: 'Cradle of Western civilization, dominated by the Parthenon.',
    imageUrl: 'https://images.unsplash.com/photo-1541270941907-3d714398c25e?w=2000',
    era: '5th Century BC'
  },
  {
    id: 'gr-2',
    nameZh: '德尔菲遗址',
    nameEn: 'Delphi',
    location: 'Phocis',
    country: 'Greece',
    continent: 'Europe',
    coordinates: { lat: 38.4824, lng: 22.4936 },
    category: 'Tangible',
    descriptionZh: '古希腊人心中的“世界中心”，阿波罗神谕所在地。',
    descriptionEn: 'The "navel of the world" in ancient Greece, site of the Oracle of Apollo.',
    imageUrl: 'https://images.unsplash.com/photo-1586095120358-35cb8d15f8f8?w=2000',
    era: '8th Century BC – 393 AD'
  },
  {
    id: 'uk-1',
    nameZh: '巨石阵',
    nameEn: 'Stonehenge',
    location: 'Wiltshire',
    country: 'United Kingdom',
    continent: 'Europe',
    coordinates: { lat: 51.1789, lng: -1.8262 },
    category: 'Tangible',
    descriptionZh: '史前巨石阵，与夏至日出完美对齐，太阳崇拜的永恒遗迹。',
    descriptionEn: 'Prehistoric monument aligned with the solstices, a masterpiece of prehistoric engineering.',
    imageUrl: 'https://images.unsplash.com/photo-1561483279-02879a5f9e6b?w=2000',
    era: '3000–2000 BC'
  },
  {
    id: 'uk-2',
    nameZh: '威斯敏斯特宫与大本钟',
    nameEn: 'Westminster Palace & Big Ben',
    location: 'London',
    country: 'United Kingdom',
    continent: 'Europe',
    coordinates: { lat: 51.4995, lng: -0.1248 },
    category: 'Tangible',
    descriptionZh: '哥特复兴式建筑巅峰，英国政治与历史的象征。',
    descriptionEn: 'Icon of British democracy, Gothic masterpiece with Elizabeth Tower.',
    imageUrl: 'https://images.unsplash.com/photo-1520986606214-8b456906c813?w=2000',
    era: '1840–1876 AD'
  },
  {
    id: 'es-1',
    nameZh: '阿尔罕布拉宫',
    nameEn: 'Alhambra',
    location: 'Granada',
    country: 'Spain',
    continent: 'Europe',
    coordinates: { lat: 37.1760, lng: -3.5881 },
    category: 'Tangible',
    descriptionZh: '摩尔人统治西班牙时期的建筑巅峰，红色宫殿与阿拉伯式花园。',
    descriptionEn: 'The finest example of Moorish architecture in Spain, a red fortress-palace.',
    imageUrl: 'https://images.unsplash.com/photo-1559827260-dc7af7cee6c9?w=2000',
    era: '1238–1492 AD'
  },
  {
    id: 'es-2',
    nameZh: '圣家族大教堂',
    nameEn: 'Sagrada Família',
    location: 'Barcelona',
    country: 'Spain',
    continent: 'Europe',
    coordinates: { lat: 41.4036, lng: 2.1744 },
    category: 'Tangible',
    descriptionZh: '高迪未完成的杰作，预计2026年竣工，现代主义建筑圣殿。',
    descriptionEn: 'Gaudí\'s unfinished masterpiece, under construction since 1882.',
    imageUrl: 'https://images.unsplash.com/photo-1583422409516-2895a441d383?w=2000',
    era: '1882 – Present'
  },
  {
    id: 'de-1',
    nameZh: '新天鹅堡',
    nameEn: 'Neuschwanstein Castle',
    location: 'Bavaria',
    country: 'Germany',
    continent: 'Europe',
    coordinates: { lat: 47.5576, lng: 10.7498 },
    category: 'Tangible',
    descriptionZh: '童话城堡，迪士尼睡美人城堡原型，巴伐利亚国王路德维希二世的梦幻之作。',
    descriptionEn: 'Fairy-tale castle that inspired Disney, built by King Ludwig II.',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=2000',
    era: '1869–1886 AD'
  },
  {
    id: 'ru-1',
    nameZh: '克里姆林宫与红场',
    nameEn: 'Kremlin and Red Square',
    location: 'Moscow',
    country: 'Russia',
    continent: 'Europe',
    coordinates: { lat: 55.7517, lng: 37.6178 },
    category: 'Tangible',
    descriptionZh: '俄罗斯政治与宗教中心，圣瓦西里大教堂的洋葱顶举世无双。',
    descriptionEn: 'Political and religious heart of Russia, with iconic onion domes.',
    imageUrl: 'https://images.unsplash.com/photo-1512499617640-c74ae3a79d37?w=2000',
    era: '12th Century – Present'
  },
  {
    id: 'tr-1',
    nameZh: '圣索菲亚大教堂',
    nameEn: 'Hagia Sophia',
    location: 'Istanbul',
    country: 'Turkey',
    continent: 'Europe',
    coordinates: { lat: 41.0086, lng: 28.9800 },
    category: 'Tangible',
    descriptionZh: '拜占庭建筑巅峰，曾为教堂、清真寺、博物馆，如今再次为清真寺。',
    descriptionEn: 'Masterpiece of Byzantine architecture, served as cathedral, mosque, and museum.',
    imageUrl: 'https://images.unsplash.com/photo-1604586375676-84c8d3bc2b58?w=2000',
    era: '537 AD'
  },
  {
    id: 'eg-1',
    nameZh: '吉萨金字塔群',
    nameEn: 'Pyramids of Giza',
    location: 'Giza, Greater Cairo',
    country: 'Egypt',
    continent: 'Africa',
    coordinates: { lat: 29.9792, lng: 31.1342 },
    category: 'Tangible',
    descriptionZh: '古埃及法老的陵墓，古代世界七大奇迹中唯一尚存的建筑。它们在沙漠中静默，诉说着永恒的渴望。',
    descriptionEn: 'The Giza Pyramid Complex, also called the Giza Necropolis, is the site on the Giza Plateau in Greater Cairo, Egypt that includes the Great Pyramid of Giza, the Pyramid of Khafre, and the Pyramid of Menkaure.',
    imageUrl: 'https://images.unsplash.com/photo-1539650116455-251d9a04a2f4?q=80&w=1974&auto=format&fit=crop',
    era: 'c. 2580–2560 BC'
  },
  {
    id: 'it-1',
    nameZh: '罗马斗兽场',
    nameEn: 'Colosseum',
    location: 'Rome, Lazio',
    country: 'Italy',
    continent: 'Europe',
    coordinates: { lat: 41.8902, lng: 12.4922 },
    category: 'Tangible',
    descriptionZh: '罗马帝国时期最大的圆形剧场，见证了角斗士的生死搏杀与帝国的兴衰。永恒之城的象征。',
    descriptionEn: 'An oval amphitheatre in the centre of the city of Rome, Italy, just east of the Roman Forum. It is the largest ancient amphitheatre ever built.',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=1996&auto=format&fit=crop',
    era: '70–80 AD'
  },
  {
    id: 'in-1',
    nameZh: '泰姬陵',
    nameEn: 'Taj Mahal',
    location: 'Agra, Uttar Pradesh',
    country: 'India',
    continent: 'Asia',
    coordinates: { lat: 27.1751, lng: 78.0421 },
    category: 'Tangible',
    descriptionZh: '莫卧儿皇帝沙·贾汗为纪念爱妻而建的白色大理石陵墓。一滴爱的泪珠，凝固在永恒的时间面颊上。',
    descriptionEn: 'An ivory-white marble mausoleum on the southern bank of the river Yamuna in the Indian city of Agra.',
    imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?q=80&w=1776&auto=format&fit=crop',
    era: '1632–1653 AD'
  },
  {
    id: 'pe-1',
    nameZh: '马丘比丘',
    nameEn: 'Machu Picchu',
    location: 'Cusco Region',
    country: 'Peru',
    continent: 'Americas',
    coordinates: { lat: -13.1631, lng: -72.5450 },
    category: 'Tangible',
    descriptionZh: '印加帝国的遗迹，被称为“失落的印加城市”。云端的城市，太阳的子民。',
    descriptionEn: 'A 15th-century Inca citadel, located in the Eastern Cordillera of southern Peru on a 2,430-metre mountain ridge.',
    imageUrl: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?q=80&w=2076&auto=format&fit=crop',
    era: 'c. 1450 AD'
  },
  {
    id: 'kh-1',
    nameZh: '吴哥窟',
    nameEn: 'Angkor Wat',
    location: 'Siem Reap',
    country: 'Cambodia',
    continent: 'Asia',
    coordinates: { lat: 13.4125, lng: 103.8667 },
    category: 'Tangible',
    descriptionZh: '世界上最大的宗教建筑群，高棉帝国建筑艺术的巅峰。石头的微笑隐藏着诸神的秘密。',
    descriptionEn: 'A temple complex in Cambodia and the largest religious monument in the world.',
    imageUrl: 'https://images.unsplash.com/photo-1600520611035-8a27863702a8?q=80&w=2069&auto=format&fit=crop',
    era: '12th Century'
  },
  {
    id: 'jo-1',
    nameZh: '佩特拉',
    nameEn: 'Petra',
    location: 'Ma\'an Governorate',
    country: 'Jordan',
    continent: 'Asia',
    coordinates: { lat: 30.3285, lng: 35.4444 },
    category: 'Tangible',
    descriptionZh: '玫瑰红色的城市，从岩石中雕刻而成。沙漠中的奇迹，纳巴泰人的宝藏。',
    descriptionEn: 'A historical and archaeological city in southern Jordan famous for its rock-cut architecture.',
    imageUrl: 'https://images.unsplash.com/photo-1579606864177-33a59828d090?q=80&w=2070&auto=format&fit=crop',
    era: 'c. 312 BC'
  },
  {
    id: 'fr-1',
    nameZh: '凡尔赛宫',
    nameEn: 'Palace of Versailles',
    location: 'Versailles',
    country: 'France',
    continent: 'Europe',
    coordinates: { lat: 48.8049, lng: 2.1204 },
    category: 'Tangible',
    descriptionZh: '法国绝对君主制的象征，以其奢华的装饰和宏大的花园而闻名。镜厅中的光影，折射出权力的辉煌。',
    descriptionEn: 'A former royal residence located in Versailles, about 12 miles west of Paris, France.',
    imageUrl: 'https://images.unsplash.com/photo-1565060169113-585a0657c79e?q=80&w=2070&auto=format&fit=crop',
    era: '1682 AD'
  },
  {
    id: 'gr-1',
    nameZh: '雅典卫城',
    nameEn: 'Acropolis of Athens',
    location: 'Athens',
    country: 'Greece',
    continent: 'Europe',
    coordinates: { lat: 37.9715, lng: 23.7257 },
    category: 'Tangible',
    descriptionZh: '古希腊文明的象征，包含帕特农神庙等著名建筑。西方文明的摇篮，理性的光辉。',
    descriptionEn: 'An ancient citadel located on a rocky outcrop above the city of Athens.',
    imageUrl: 'https://images.unsplash.com/photo-1541270941907-3d714398c25e?q=80&w=1935&auto=format&fit=crop',
    era: '5th Century BC'
  },
  {
    id: 'mx-1',
    nameZh: '奇琴伊察',
    nameEn: 'Chichen Itza',
    location: 'Yucatán',
    country: 'Mexico',
    continent: 'Americas',
    coordinates: { lat: 20.6843, lng: -88.5678 },
    category: 'Tangible',
    descriptionZh: '玛雅文明的伟大城市，库库尔坎金字塔见证了精妙的天文历法。羽蛇神的降临之地。',
    descriptionEn: 'A large pre-Columbian city built by the Maya people of the Terminal Classic period.',
    imageUrl: 'https://images.unsplash.com/photo-1518638150340-f706e8403698?q=80&w=2025&auto=format&fit=crop',
    era: 'c. 600–1200 AD'
  }
];

// 程序生成填充项（保持你原来的逻辑）
const generateProceduralItems = (count: number): HeritageItem[] => {
  const fillers: HeritageItem[] = [];
  const continents = ['Asia', 'Europe', 'Africa', 'Americas', 'Oceania'] as const;

  for (let i = 0; i < count; i++) {
    fillers.push({
      id: `proc-${i}`,
      nameZh: '未名遗产',
      nameEn: 'Unrecorded Heritage',
      location: 'Unknown',
      country: 'Unknown',
      continent: continents[Math.floor(Math.random() * continents.length)],
      coordinates: { lat: 0, lng: 0 },
      category: 'Tangible',
      descriptionZh: '历史长河中的璀璨星辰。',
      descriptionEn: 'A shining star in the river of history.',
      imageUrl: `https://picsum.photos/seed/history${i}/1600/900`,
      era: 'Ancient',
      isProcedural: true
    } as HeritageItem);
  }
  return fillers;
};


export const HERITAGE_ITEMS: HeritageItem[] = [
  ...FEATURED_HERITAGE_ITEMS,
  ...generateProceduralItems(1200 - FEATURED_HERITAGE_ITEMS.length)
];


export const POETRY_DATABASE: any = {
  'China': [
    { line: '大江东去，浪淘尽，千古风流人物。', translation: 'The Great River flows east, washing away the gallant heroes of antiquity.', author: 'Su Shi', year: '1082 AD' },
    { line: '秦时明月汉时关。', translation: 'The moon of Qin times shines on the pass of Han.', author: 'Wang Changling', year: '740 AD' }
  ],
  'default': [
    { line: 'History is a philosophy teaching by examples.', translation: '历史是以榜样进行教导的哲学。', author: 'Thucydides', year: '400 BC' }
  ]
  
};
