// services/constants.ts —— 终极完美版（只保留真实遗产 + 中英文永不闪退）
import { HeritageItem } from '../types';

export const UI_TEXT = {
  zh: {
    title: '为什么湘江北去？',
    subtitle: '因为世界上所有的水都是湘江之水，包括泪水',
    back: '返回',
    history: '历史',
    related: '相关遗址',
    reimagine: '重想象此地',
    prompt: '用文字描述你想看到的样子...',
    generate: '生成',
    generating: '生成中...',
    download: '下载'
  },
  en: {
    title: 'Why Does the Xiang River Flow North?',
    subtitle: 'Because all water in the world is Xiang River water — including tears',
    back: 'Back',
    history: 'History',
    related: 'Related Sites',
    reimagine: 'Reimagine This Place',
    prompt: 'Describe what you want to see...',
    generate: 'Generate',
    generating: 'Generating...',
    download: 'Download'
  }
} as const;

// 20个全球顶尖真实世界遗产（全部真实！无任何程序生成）
export const HERITAGE_ITEMS: HeritageItem[] = [
  {
    id: 'cn-1',
    nameZh: '万里长城',
    nameEn: 'The Great Wall',
    location: 'Beijing / Northern China',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 40.4319, lng: 116.5704 },
    category: 'Tangible',
    descriptionZh: '世界上最长的防御工事，横跨15个省份，如巨龙守护华夏。',
    descriptionEn: 'The longest wall in the world, a dragon across mountains.',
    imageUrl: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=2000',
    era: '7th Century BC - 1644 AD'
  },
  {
    id: 'cn-2',
    nameZh: '北京故宫',
    nameEn: 'Forbidden City',
    location: 'Beijing',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 39.9163, lng: 116.3972 },
    category: 'Tangible',
    descriptionZh: '明清两代皇宫，世界最大木结构古建筑群。',
    descriptionEn: 'Imperial palace of Ming and Qing dynasties.',
    imageUrl: 'https://images.unsplash.com/photo-1517332712256-6fb136b2d6a3?w=2000',
    era: '1406–1912 AD'
  },
  {
    id: 'cn-3',
    nameZh: '秦始皇陵及兵马俑',
    nameEn: 'Terracotta Army',
    location: 'Xi\'an',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 34.3841, lng: 109.2784 },
    category: 'Tangible',
    descriptionZh: '8000尊陶俑组成的地下军队，秦始皇的永恒卫队。',
    descriptionEn: '8,000 life-sized warriors guarding the First Emperor.',
    imageUrl: 'https://images.unsplash.com/photo-1538333702850-03aa4a7b9b6b?w=2000',
    era: '221–210 BC'
  },
  {
    id: 'cn-4',
    nameZh: '敦煌莫高窟',
    nameEn: 'Mogao Caves',
    location: 'Dunhuang',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 40.0374, lng: 94.8042 },
    category: 'Tangible',
    descriptionZh: '丝绸之路佛教艺术宝库，492个石窟，45000平米壁画。',
    descriptionEn: 'Greatest repository of Buddhist art on the Silk Road.',
    imageUrl: 'https://images.unsplash.com/photo-1627894486535-251d9a04a2f4?w=2000',
    era: '366–1368 AD'
  },
  {
    id: 'cn-5',
    nameZh: '布达拉宫',
    nameEn: 'Potala Palace',
    location: 'Lhasa',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 29.6573, lng: 91.1172 },
    category: 'Tangible',
    descriptionZh: '世界海拔最高的宫殿，藏式建筑巅峰之作。',
    descriptionEn: 'Highest palace in the world.',
    imageUrl: 'https://images.unsplash.com/photo-1553272725-086100aecf5e?w=2000',
    era: '7th Century – 1645 AD'
  },
  {
    id: 'cn-6',
    nameZh: '丽江古城',
    nameEn: 'Old Town of Lijiang',
    location: 'Lijiang',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 26.8720, lng: 100.2337 },
    category: 'Tangible',
    descriptionZh: '纳西族古城，无城墙的东方威尼斯。',
    descriptionEn: 'Naxi ancient town, Venice of the East.',
    imageUrl: 'https://images.unsplash.com/photo-1558499933-9a08e3d1d7c8?w=2000',
    era: 'Song Dynasty – Present'
  },
  {
    id: 'cn-7',
    nameZh: '苏州古典园林',
    nameEn: 'Classical Gardens of Suzhou',
    location: 'Suzhou',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 31.3160, lng: 120.6180 },
    category: 'Tangible',
    descriptionZh: '中国私家园林巅峰，拙政园、留园等9座园林。',
    descriptionEn: 'Pinnacle of Chinese classical garden design.',
    imageUrl: 'https://images.unsplash.com/photo-1593697821252-0c3f8d3b2394?w=2000',
    era: '11th–19th Century'
  },
  {
    id: 'cn-8',
    nameZh: '颐和园',
    nameEn: 'Summer Palace',
    location: 'Beijing',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 39.9990, lng: 116.2700 },
    category: 'Tangible',
    descriptionZh: '清代皇家园林，集中国古典园林之大成。',
    descriptionEn: 'Masterpiece of Chinese imperial garden.',
    imageUrl: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=2000',
    era: '1750–1888 AD'
  },
  {
    id: 'cn-9',
    nameZh: '承德避暑山庄',
    nameEn: 'Mountain Resort, Chengde',
    location: 'Chengde',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 40.9900, lng: 117.9400 },
    category: 'Tangible',
    descriptionZh: '清代最大的皇家园林，康熙乾隆行宫。',
    descriptionEn: 'Largest imperial garden of Qing Dynasty.',
    imageUrl: 'https://images.unsplash.com/photo-1588421277-5e8e7e5d9e7e?w=2000',
    era: '1703–1792 AD'
  },
  {
    id: 'cn-10',
    nameZh: '龙门石窟',
    nameEn: 'Longmen Grottoes',
    location: 'Luoyang',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 34.5552, lng: 112.4700 },
    category: 'Tangible',
    descriptionZh: '北魏至唐代佛教石窟，卢舍那大佛高17.14米。',
    descriptionEn: 'Buddhist grottoes with 17.14m Lushena Buddha.',
    imageUrl: 'https://images.unsplash.com/photo-1593693411134-8e6d1d64e1e9?w=2000',
    era: '493–1127 AD'
  },
  {
    id: 'cn-11',
    nameZh: '中医针灸',
    nameEn: 'Acupuncture',
    location: 'Nationwide',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 35.0000, lng: 105.0000 },
    category: 'Intangible',
    descriptionZh: '中国传统医学核心技艺，2010年UNESCO非遗。',
    descriptionEn: 'Core technique of Traditional Chinese Medicine.',
    imageUrl: 'https://images.unsplash.com/photo-1603393938459-0b3b1d2d8c3e?w=2000',
    era: 'Ancient – Present'
  },
  {
    id: 'cn-12',
    nameZh: '京剧',
    nameEn: 'Peking Opera',
    location: 'Beijing & Nationwide',
    country: 'China',
    continent: 'Asia',
    coordinates: { lat: 39.9042, lng: 116.4074 },
    category: 'Intangible',
    descriptionZh: '中国国粹，唱念做打，脸谱艺术。',
    descriptionEn: 'Quintessence of Chinese culture.',
    imageUrl: 'https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?w=2000',
    era: '1790 – Present'
  },
  {
    id: 'eg-1',
    nameZh: '吉萨金字塔群',
    nameEn: 'Pyramids of Giza',
    location: 'Giza',
    country: 'Egypt',
    continent: 'Africa',
    coordinates: { lat: 29.9792, lng: 31.1342 },
    category: 'Tangible',
    descriptionZh: '古代世界七大奇迹唯一幸存者。',
    descriptionEn: 'Last remaining ancient wonder.',
    imageUrl: 'https://images.unsplash.com/photo-1539650116455-251d9a04a2f4?w=2000',
    era: 'c. 2580–2560 BC'
  },
  {
    id: 'it-1',
    nameZh: '罗马斗兽场',
    nameEn: 'Colosseum',
    location: 'Rome',
    country: 'Italy',
    continent: 'Europe',
    coordinates: { lat: 41.8902, lng: 12.4922 },
    category: 'Tangible',
    descriptionZh: '古罗马最大圆形剧场，可容8万人。',
    descriptionEn: 'Largest ancient amphitheatre.',
    imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=2000',
    era: '70–80 AD'
  },
  {
    id: 'in-1',
    nameZh: '泰姬陵',
    nameEn: 'Taj Mahal',
    location: 'Agra',
    country: 'India',
    continent: 'Asia',
    coordinates: { lat: 27.1751, lng: 78.0421 },
    category: 'Tangible',
    descriptionZh: '一滴爱凝成的永恒之泪。',
    descriptionEn: 'A teardrop on the cheek of time.',
    imageUrl: 'https://images.unsplash.com/photo-1548013146-72479768bada?w=2000',
    era: '1632–1653 AD'
  },
  {
    id: 'pe-1',
    nameZh: '马丘比丘',
    nameEn: 'Machu Picchu',
    location: 'Cusco',
    country: 'Peru',
    continent: 'Americas',
    coordinates: { lat: -13.1631, lng: -72.5450 },
    category: 'Tangible',
    descriptionZh: '印加帝国云端之城。',
    descriptionEn: 'Lost city of the Incas.',
    imageUrl: 'https://images.unsplash.com/photo-1587595431973-160d0d94add1?w=2000',
    era: 'c. 1450 AD'
  },
  {
    id: 'kh-1',
    nameZh: '吴哥窟',
    nameEn: 'Angkor Wat',
    location: 'Siem Reap',
    country: 'Cambodia',
    continent: 'Asia',
    coordinates: { lat: 13.4125, lng: 103.8667 },
    category: 'Tangible',
    descriptionZh: '世界上最大的宗教建筑群。',
    descriptionEn: 'Largest religious monument in the world.',
    imageUrl: 'https://images.unsplash.com/photo-1600520611035-8a27863702a8?w=2000',
    era: '12th Century'
  },
  {
    id: 'jo-1',
    nameZh: '佩特拉',
    nameEn: 'Petra',
    location: 'Ma\'an',
    country: 'Jordan',
    continent: 'Asia',
    coordinates: { lat: 30.3285, lng: 35.4444 },
    category: 'Tangible',
    descriptionZh: '玫瑰红色的石头之城。',
    descriptionEn: 'Rose-red city half as old as time.',
    imageUrl: 'https://images.unsplash.com/photo-1579606864177-33a59828d090?w=2000',
    era: 'c. 312 BC'
  },
  {
    id: 'fr-1',
    nameZh: '凡尔赛宫',
    nameEn: 'Palace of Versailles',
    location: 'Versailles',
    country: 'France',
    continent: 'Europe',
    coordinates: { lat: 48.8049, lng: 2.1204 },
    category: 'Tangible',
    descriptionZh: '太阳王路易十四的奢华宫殿。',
    descriptionEn: 'Sun King\'s palace of absolute monarchy.',
    imageUrl: 'https://images.unsplash.com/photo-1565060169113-585a0657c79e?w=2000',
    era: '1682 AD'
  },
  {
    id: 'gr-1',
    nameZh: '雅典卫城',
    nameEn: 'Acropolis of Athens',
    location: 'Athens',
    country: 'Greece',
    continent: 'Europe',
    coordinates: { lat: 37.9715, lng: 23.7257 },
    category: 'Tangible',
    descriptionZh: '西方文明的摇篮。',
    descriptionEn: 'Cradle of Western civilization.',
    imageUrl: 'https://images.unsplash.com/photo-1541270941907-3d714398c25e?w=2000',
    era: '5th Century BC'
  },
  {
    id: 'mx-1',
    nameZh: '奇琴伊察',
    nameEn: 'Chichen Itza',
    location: 'Yucatán',
    country: 'Mexico',
    continent: 'Americas',
    coordinates: { lat: 20.6843, lng: -88.5678 },
    category: 'Tangible',
    descriptionZh: '玛雅最伟大的城市。',
    descriptionEn: 'Greatest city of the Maya.',
    imageUrl: 'https://images.unsplash.com/photo-1518638150340-f706e8403698?w=2000',
    era: 'c. 600–1200 AD'
  }
];

// 不再生成任何“未名遗产”！只有真实遗产！
export const POETRY_DATABASE: any = {
  'China': [
    { line: '大江东去，浪淘尽，千古风流人物。', translation: 'The Great River flows east, washing away the gallant heroes of antiquity.', author: 'Su Shi', year: '1082 AD' },
    { line: '秦时明月汉时关。', translation: 'The moon of Qin times shines on the pass of Han.', author: 'Wang Changling', year: '740 AD' }
  ],
  'default': [
    { line: 'History is a philosophy teaching by examples.', translation: '历史是以榜样进行教导的哲学。', author: 'Thucydides', year: '400 BC' }
  ]
};
